### PR TITLE
Fixed missing Vuestic UI logo

### LINKED ISSUE #366: [BUG] Vuestic UI logo issing
**Describe the bug**
Vuestic UI on the Vue Libraries is missing a logo: https://vue.framework.dev/categories/libraries

Screen Shot 2022-10-29 at 12 54 59 PM

Use the logo from their website: https://vuestic.dev/

### PR DESCRIPTION
**Pull request by suchitd11**
## Type of change

- [ ] Content addition
- [x] Bug fix
- [ ] Behavior change

## Summary of change
Added a PNG of Vuestic UI logo in public folder, and linked that image in the libraries file

## Checklist

- [x] This fix resolves #366
- [x] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [x] I have verified the fix works and introduces no further errors

### CODE REVIEW

**Comment by suchitd11** [comment]
@dustinsgoodman please accept my pull request!

**Comment by suchitd11** [comment]
okay

**Comment by suchitd11** [comment]
@jdwilkin4 done!

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Thank you for making those changes.

When I tested this out the logo is really small
Screen Shot 2022-10-30 at 9 37 36 AM

Can we find another logo?
You can test your changes locally and with the amplify links provides in the PR 👍

**Comment by suchitd11** [comment]
@jdwilkin4 I took that logo from vuestic ui repo but actually the problem is the size of logo is rectangular and the size in the website is square. So that's why it looks like that.

**Comment by suchitd11** [comment]
@jdwilkin4 https://vuestic.dev/favicon-32x32.png should i add this one then?

**Comment by jdwilkin4** [comment]
@suchitd11 
Yes, test it out locally but it looks like that will work

**Comment by suchitd11** [comment]
image
will this work?

**Comment by jdwilkin4** [comment]
Yes, that should work.
Please push up your changes so I can see it with the amplify link.
But it looks like it should be fine

**Comment by suchitd11** [comment]
okay!

**Comment by suchitd11** [comment]
updated

**Review by jdwilkin4 — APPROVED** [review]
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

**Pull request merged**
