### PR TITLE
Added "React - The Road To Enterprise" book

### PR DESCRIPTION
**Pull request by ThomasFindlay**

### CODE REVIEW

**Comment by torontodeveloper** [comment]
Since there is lot of mock static data, can we extract all  as json file/ts file and import, that way mock data is extracted which is usually best practice in production code by separation of concern, i don't know, just  a thought
import  bookslist from './booklist.json'
export const books:Book<typeof bookTags[number]>[]= bookslist 

booklist.json 
[{

}]

**Review by tvanantwerp — CHANGES_REQUESTED** [review]
Thanks for your patience!

The data looks good. But the description is a bit long compared to other books. Would you be able to condense to something closer to 300 characters?

The difference in the height of the cover image versus others appears to be an oversight on our end, and we'll work on that.

image

**Comment by ThomasFindlay** [comment]
> Thanks for your patience!
> 
> The data looks good. But the description is a bit long compared to other books. Would you be able to condense to something closer to 300 characters?
> 
> The difference in the height of the cover image versus others appears to be an oversight on our end, and we'll work on that.
> 
> image

Hey. Thanks for the feedback. I just shortened the text. I tried to get it as close to 300 characters as I can. Is it alright now or would you like me to reduce it even further?

**Review by tvanantwerp — APPROVED** [review]
Looks great! Thanks for the contribution!

**Pull request merged**
