### PR TITLE
Create GameDevSummit_logo.png

### LINKED ISSUE #364: [BUG] Charka UI missing logo
**Describe the bug**
Chakra UI on the Vue Libraries is missing a logo: https://vue.framework.dev/categories/libraries

Screen Shot 2022-10-29 at 12 52 39 PM

Use the logo from their website: https://chakra-ui.com/

### LINKED ISSUE #368: [BUG] GameDev Summit logo is illegible
**Describe the bug**

The GameDev Summit logo on https://vue.framework.dev/categories/communities (but also the react and angular sites) is not legible due to the png not having a contrasting background color. 

Current:
Screen Shot 2022-10-29 at 12 59 06 PM

What's missing:
Screen Shot 2022-10-29 at 12 59 52 PM

Replace this logo with one that allows users to see the full logo.

### PR DESCRIPTION
**Pull request by DJDevon3**
Legible no matter the background color. PNG format as requested.

## Type of change

- [ ] Content addition
- [x] Bug fix
- [ ] Behavior change

## Summary of change

Designed GameDev Summit logo to be legible with transparency no matter the background color.

## Checklist

- [x] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [x] I have searched all existing content and verified my additions are novel
      and unique

- [ ] This fix resolves #368, fixes #364
- [x] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [ x] I have verified the fix works and introduces no further errors

### CODE REVIEW

**Comment by jdwilkin4** [comment]
HI @DJDevon3 ! 

I updated your PR to include that this also fixes the chakra ui icon.

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Hi @DJDevon3 ! 

Please remove this images from the example-assets folder.
For the JS Game Summit, we need you to replace the existing image links for all three react, angular, and vue sites.
Here are the files you need to look at
```
framework.dev/packages/site/src/data/angular/communities.ts
framework.dev/packages/site/src/data/react/communities.ts
framework.dev/packages/site/src/data/vue/communities.ts
```
In each of those files, you will see the entries for the game dev summit

```
{
		name: "JS Game Dev Summit",
		description:
			"JavaScript GameDev Summit is a 2-day online event for engineers, technical artists, and creative developers who develop games and graphics-heavy applications with Web technology. ",
		image: "https://jsgamedev.com/img/logo.svg",
		type: "Live Events",
		href: "https://jsgamedev.com/",
		tags: ["conferences"],
	},
```
For the Chakra logo, you will need to look at the `framework.dev/packages/site/src/data/vue/libraries.ts` file

We need you to add the logo for Charka here
```
	{
		name: "Chakra UI",
		author: "Jonathan Bakebwa",
		gitHubRepo: "chakra-ui/chakra-ui-vue",
		npmPackage: "@chakra-ui/vue",
		href: "https://vue.chakra-ui.com/",
		description:
			"Chakra UI gives you a set of accessible and composable Vue components that you can use to build your favourite applications and sites. Made for Vue 2.X",
		image: "",
		tags: ["component library", "Vue 2"],
	},
```
Please test your changes locally and by also checking the generated amplify links in the PR 👍

**Comment by DJDevon3** [comment]
Where do you want me to upload the new SVG though? In /public for each of the the sites? I'm just scouring hacktoberfest for easy issues. A png or svg redesign I can do. I don't know anything about your framework, react, angular, or vue.

**Comment by jdwilkin4** [comment]
We don't need you to upload any new SVG's. We just want you to change the image links in the files mentioned earlier. 
If it helps, here is a merged PR  fixing some other broken image links to give you an idea what you need to do.
https://github.com/thisdot/framework.dev/pull/256/files

Hope that is clearer 👍

**Comment by zafar-hussain** [comment]
Hi, @DJDevon3,

You can use the logo from their GitHub repos, 
Use a link from [chakraui logos](https://github.com/chakra-ui/chakra-ui/tree/main/logo).

Similarly, look for the logo for JsGameDev in their repo.

Cheers

**Comment by DJDevon3** [comment]
The issue description says "Replace this logo with one that allows users to see the full logo." Now you're saying it's actually about fixing broken image links and in files that are framework.dev/packages/site/src/data/angular/communities.ts 5 layers deep in an obscure ts file... I really don't feel like jumping through so many hoops in a framework I'm not familiar with and have no intention to ever use. I was just trying to hit some low hanging graphic fruit for hacktoberfest submissions only to find out this one isn't what it was described.

**Pull request closed without merging**
