### PR TITLE
Content: update library tags and languages

### PR DESCRIPTION
**Pull request by mbicknese**
## Type of change

- [x] Content addition
- [ ] Bug fix
- [ ] Behavior change

## Summary of change

Update all libraries with appropriate languages and tags.

## Checklist

- [x] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [x] I have searched all existing content and verified my additions are novel
      and unique
- [x] All required content fields are accurately populated
- [x] All items are tagged with all relevant tags

Closes: #556 
Closes: #585

### CODE REVIEW

**Comment by iansamz** [comment]
Noted the libraries are not showing up when a tag is selected from the sidebar.
image

**Comment by mbicknese** [comment]
@iansamz are the filters curated, or is it just something that happened over time? I've tried to unify all tags, which made have been a wrong move if we want specific filters like these. Two options moving forward are, we filter by the new tags we have (I can auto cherry pick the tags used per framework). Or I can "clutter" the unified tags with the very specific tags.

CC @kenslachtajr

**Comment by iansamz** [comment]
Sorry @mbicknese. Hadn't seen your comment.  We can create another PR to auto cherry-pick the tags per framework @kenslachtajr

**Comment by mbicknese** [comment]
The change was easy enough to implement quickly. Curious to know whether this is a step in the right direction. We can reconsider the tags we have and how libs are tagged.

**Review by SDaian — APPROVED** [review]
LGTM

**Review by jdwilkin4 — COMMENTED** [review]
I think this looks good. 👍 
It looks like some of the builds are failing though.

**Review by SDaian — APPROVED** [review]
💯

**Pull request merged**
