### PR TITLE
make featured library name dynamic with `SNOWPACK_PUBLIC_FRAMEWORK`

### LINKED ISSUE #186: [BUG] Featured libraries text is hard coded to React
**Describe the bug**
When running the Angular version locally, noticed that the library section says "Featured React libraries". Looking inside the code, this text (React) is hard coded into the site. Will want this to be dynamic based on the version of the site you're on.

**To Reproduce**
1. Run `yarn dev:angular` and load the localhost page
2. Scroll down to the featured libraries section of the homepage

**Expected behavior**
Text should read "Featured Angular libraries"

**Screenshots**
Screen Shot 2022-04-13 at 5 53 20 PM

**Desktop (please complete the following information):**
 - OS: MacOS Monterrey 12.3.1
 - Browser: Chrome
 - Version 100

### PR DESCRIPTION
**Pull request by iaremarkus**
## Type of change

- [ ] Content addition
- [x] Bug fix
- [ ] Behavior change

## Summary of change

Use the `SNOWPACK_PUBLIC_FRAMEWORK` environment variable to make the `Featured {library} Library` name dynamic. 

Hope you don't mind me snagging this one @lindakatcodes 😊

## Checklist

- [x] I have added a line to the [changelog](../CHANGELOG.md) with the current
      date, change, PR number and author

- [x] This fix resolves #186 
- [x] The changes follow the [contributing guidelines](../CONTRIBUTING.md)
- [x] I have verified the fix works and introduces no further errors

### CODE REVIEW

**Review by tvanantwerp — CHANGES_REQUESTED** [review]
This is a good catch!

I'd like it, though, if instead of referencing the `SNOWPACK_PUBLIC_FRAMEWORK` from inside the `system` package, we just make the name a component prop and feed that name from inside its use in the `site` package where all other references to that `env` variable reside. That way, this component remains decoupled from the `site` package, and if the `site` were radically altered (change of framework, change of env names, whatever) the component itself wouldn't be affected.

**Comment by iaremarkus** [comment]
Awesome, I'll give this a crack in the week @tvanantwerp 👌

**Comment by jesus4497** [comment]
I will close this PR as it was fixed in #197 !

**Comment by dustinsgoodman** [comment]
@iaremarkus thank you for your contribution! We were in a bit of a hurry to get this change in as we're trying to release some new versions of the site. We really appreciated you taking a stab at this. It definitely influenced the solution that's in place now. ❤️

**Comment by iaremarkus** [comment]
Gosh you are all so polite 😊 

Soz @dustinsgoodman, I've been man-down with flu the last week or so, so my apologies for not getting onto this quicker... 💯 happy that y'all went ahead with a solution.

🖤🤜🤛

**Pull request closed without merging**
