### PR TITLE
[BUG] Agnostic UI logo missing  Fixes #367

### LINKED ISSUE #367: [BUG] Agnostic UI logo missing
**Describe the bug**
Vuestic UI on the Vue Libraries is missing a logo: https://vue.framework.dev/categories/libraries

Screen Shot 2022-10-29 at 12 55 03 PM

Use the logo from their website: https://www.agnosticui.com/

### PR DESCRIPTION
**Pull request by zafar-hussain**
## Type of change

- [ ] Content addition
- [x] Bug fix
- [ ] Behavior change

## Summary of change

Agnostic UI was logo missing from libraries.ts in vue

## Checklist

- [x] This fix resolves #367
- [x] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [ ] I have verified the fix works and introduces no further errors

### CODE REVIEW

**Review by dustinsgoodman — CHANGES_REQUESTED** [review]
The image you chose isn't quite working. See the preview deploy: https://pr-373.d7tvjh0fjnmfb.amplifyapp.com/categories/libraries


image

**Comment by zafar-hussain** [comment]
Hi @dustinsgoodman,

sorry about that,
something is definitely wrong here, 
let me sort it out

cheers

**Comment by zafar-hussain** [comment]
Hi @dustinsgoodman,

I have changed the logo for AgnosticUI,

Please check and advise,

cheers

**Review by jdwilkin4 — APPROVED** [review]
Congrats on another contribution to our repository. 🎉
We look forward to future contributions. 👍

**Pull request merged**
