### PR TITLE
Feature/add resource

### PR DESCRIPTION
**Pull request by akilah-littlejohn**
## Type of change

- [x] Content addition
- [ ] Bug fix
- [ ] Behavior change

## Checklist

- [ ] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [ ] I have searched all existing content and verified my additions are novel
      and unique
- [ ] The content was added to the end of the appropriate data list
- [ ] All required content fields are accurately populated
- [ ] All items are tagged with all relevant tags

- [ ] This fix resolves #
- [ ] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [ ] I have verified the fix works and introduces no further errors

- [ ] This change resolves #
- [ ] I have confirmed with a maintainer that this change is desired and been
      given the go-ahead to work on it in the relevant issue discussion
- [ ] The changes follow the [contributing guidelines](https://github.com/thisdot/framework.dev/blob/main/CONTRIBUTING.md)
- [ ] I have verified the change and the rest of the site works as expected
- [ ] If the change introduces new components, these have been added to
      `packages/system/src/components` with a `.stories.tsx` file that
      adequately renders possible variations of each component.

### CODE REVIEW

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Comment by ryfazrin** [comment]
Hello @jdwilkin4
Thank you for giving me the opportunity to contribute. My PR seems to have failed to deploy, what should I do?

**Comment by jdwilkin4** [comment]
HI @ryfazrin 
If you are having issues with creating a PR, then you can reach out to the Discord community and someone can assist you there. 
https://discord.gg/3uACbKtJ

**Comment by ryfazrin** [comment]
> HI @ryfazrin If you are having issues with creating a PR, then you can reach out to the Discord community and someone can assist you there. https://discord.gg/3uACbKtJ

Yes, thank you @jdwilkin4

**Pull request merged**
